name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Genera Canale 1 (Pluto TV Film)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["608aa17fb9f4490007e6419a"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale1.m3u8

      - name: Genera Canale 2 (Pluto TV Film Azione)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["608aa20a2e7f270007c4878d"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale2.m3u8

      - name: Genera Canale 3 (Pluto TV Azione Cult)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["6994800c470389f33df8e090"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale3.m3u8

      - name: Genera Canale 4 (Pluto TV Horror)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["61c09e3ac210ed0007606620"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale4.m3u8

      - name: Genera Canale 5 (Pluto TV Film Thriller)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["608aa5e995132a00075f7005"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale5.m3u8

      - name: Genera Canale 6 (Pluto TV Legami Letali)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["64808a8c536e0c0008a276d1"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale6.m3u8

      - name: Genera Canale 7 (Pluto TV Film Romantici)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["608aa4a4cc92820007b663af"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json && mv output/plutotv_it.m3u8 output/canale7.m3u8

      - name: Genera Canale 8 (Pluto TV Film Commedia)
        run: |
          echo '{"outdir":"./output","clientID":"","mapping":{"it":"2.112.0.1"},"all":false,"regionalize":true,"includeChannels":["608aa512d67fd900072323db"],"randomClientid":true}' > tmp.json
          node index.js --config tmp.json &&
