name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Forza Generazione M3U8 e Avvia Script
        run: |
          # Modifica temporanea per forzare lo scraper a generare il file .m3u8 dell'Italia
          sed -i 's/"mapping": {/"mapping": {"it": "2.112.0.1",/g' config.json
          node index.js

      - name: Salvataggio file su GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Forzato il rilascio di plutotv_it.m3u8 ed EPG" || echo "No changes"
          git push --force origin main
